version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Sao_Paulo"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependabot"
    assignees:
      - "pedro-pm-dias"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
      timezone: "America/Sao_Paulo"
    rebase-strategy: "auto"
    labels:
      - "dependabot"
    assignees:
      - "pedro-pm-dias"
